src/DMTP.REST/Models/Setup/SetupModel.cs
using System.ComponentModel.DataAnnotations;

namespace DMTP.REST.Models.Setup
{
    public class SetupModel
    {
        public string ActionMessage { get; set; }

        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        public string EmailAddress { get; set; }

        [Required]
        public string Password { get; set; }

        [Required]
        public string SMTPHostName { get; set; }

        [Required]
        public string SMTPUsername { get; set; }

        [Required]
        public string SMTPPassword { get; set; }

        [Required]
        public int SMTPPortNumber { get; set; }

        [Required]
        public bool AllowUserCreation { get; set; }
    }
}

src/DMTP.REST/Controllers/SetupController.cs
using System.Linq;

using DMTP.lib.Common;
using DMTP.lib.dal.Databases.Tables;
using DMTP.lib.dal.Manager;
using DMTP.lib.Helpers;
using DMTP.lib.Managers;
using DMTP.lib.Security;
using DMTP.REST.Models.Setup;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;

namespace DMTP.REST.Controllers
{
    public class SetupController : BaseController
    {
        private readonly SetupManager _setupManager;

        private IStringLocalizer<SetupController> _localizer;

        public SetupController(DatabaseManager database, Settings settings, IStringLocalizer<SetupController> localizer) : base(database, settings)
        {
            _setupManager = new SetupManager(Database);

            _localizer = localizer;
        }

        public IActionResult Index(SetupModel model = null)
        {
            if (CurrentSettings.IsInitialized)
            {
                return RedirectToAction("Index", "Account");
            }

            _setupManager.Initialize();

            return View(model ?? new SetupModel());
        }

        public IActionResult AttemptSetup(SetupModel model)
        {
            if (!ModelState.IsValid)
            {
                model.ActionMessage = _localizer["EnsureAllFieldsAreFilledOut"];

                return RedirectToAction("Index", new {model = model});
            }

            CurrentSettings.IsInitialized = true;
            CurrentSettings.AllowNewUserCreation = model.AllowUserCreation;
            CurrentSettings.SMTPHostName = model.SMTPHostName;
            CurrentSettings.SMTPPassword = model.SMTPPassword;
            CurrentSettings.SMTPPortNumber = model.SMTPPortNumber;
            CurrentSettings.SMTPUsername = model.SMTPUsername;
            CurrentSettings.DeviceKeyPassword = Strings.GenerateRandomString();

            new SettingManager(Database).UpdateSettings(CurrentSettings);

            var adminRole = new RoleManager(Database).GetRoles().FirstOrDefault(a => a.Name == Constants.ROLE_BUILTIN_ADMIN);

            if (adminRole == null)
            {
                model.ActionMessage = _localizer["AdminRoleNotFound"];

                return RedirectToAction("Index", model);
            }

            var user = new UserManager(Database).CreateUser(model.EmailAddress, model.FirstName, model.LastName, model.Password.ToSHA1(), adminRole.ID);

            if (user != null)
            {
                return Login(user.Value, model.EmailAddress);
            }

            model.ActionMessage = _localizer["FailedToCreateUser"];

            return RedirectToAction("Index", model);
        }
    }
}

src/DMTP.REST/Views/Setup/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

@model DMTP.REST.Models.Setup.SetupModel

@{
    Layout = "~/Views/Shared/_LayoutUnauthenticated.cshtml";
    ViewData["Title"] = Localizer["PageTitle"];
}

<h3>@Localizer["Header"]</h3>

@if (!string.IsNullOrEmpty(Model.ActionMessage))
{
    <div class="alert alert-primary">
        @Model.ActionMessage
    </div>
}

<form method="post" asp-controller="Setup" asp-action="AttemptSetup" class="form-signin form">
    <h5 class="text-white">@Localizer["AdministratorAccountHeader"]</h5>
    <div class="form-label-group">
        <label>@Localizer["FirstNameLabel"]</label>
        <input class="form-control" type="text" asp-for="@Model.FirstName" required />
    </div>

    <div class="form-label-group">
        <label>@Localizer["LastNameLabel"]</label>
        <input class="form-control" type="text" asp-for="@Model.LastName" required />
    </div>

    <div class="form-label-group">
        <label>@Localizer["EmailAddressLabel"]</label>
        <input class="form-control" type="text" asp-for="@Model.EmailAddress" required />
    </div>

    <div class="form-label-group">
        <label>@Localizer["PasswordLabel"]</label>
        <input class="form-control" type="text" asp-for="@Model.Password" required />
    </div>

    <br />

    <h5 class="text-white">@Localizer["SMTPSettingsHeader"]</h5>
    <div class="form-label-group">
        <label>@Localizer["HostNameLabel"]</label>
        <input class="form-control" type="text" asp-for="@Model.SMTPHostName" />
    </div>

    <div class="form-label-group">
        <label>@Localizer["PortNumberLabel"]</label>
        <input class="form-control" type="text" asp-for="@Model.SMTPPortNumber" />
    </div>

    <div class="form-label-group">
        <label>@Localizer["UserNameLabel"]</label>
        <input class="form-control" type="text" asp-for="@Model.SMTPUsername" />
    </div>

    <div class="form-label-group">
        <label>@Localizer["PasswordLabel"]</label>
        <input class="form-control" type="password" asp-for="@Model.SMTPPassword" />
    </div>

    <br />

    <h5 class="text-white">@Localizer["MiscSettingsLabel"]</h5>

    <div class="form-label-group">
        <label asp-for="AllowUserCreation">@Localizer["AllowNewUserCreationLabel"]</label>
        <input class="form-control" type="checkbox" asp-for="@Model.AllowUserCreation" />
    </div>

    <br />

    <input type="submit" value="@Localizer["CompleteSetupButton"]" class="btn btn-lg btn-primary btn-block text-uppercase" />
</form>