src/DMTP.REST/Controllers/AssembliesController.cs
using System;
using System.IO;

using DMTP.lib.dal.Databases.Tables;
using DMTP.lib.dal.Enums;
using DMTP.lib.dal.Manager;

using DMTP.lib.Managers;

using DMTP.REST.Attributes;
using DMTP.REST.Models.Assemblies;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;

namespace DMTP.REST.Controllers
{
    [Authorize]
    public class AssembliesController : BaseController
    {
        private readonly IStringLocalizer<AssembliesController> _localizer;

        public AssembliesController(DatabaseManager database, Settings settings, IStringLocalizer<AssembliesController> localizer) : base(database, settings)
        {
            _localizer = localizer;
        }

        [HttpPost]
        [Access(AccessSections.ASSEMBLIES, AccessLevels.EDIT)]
        public IActionResult UploadAssembly(IFormFile file)
        {
            using (var ms = new MemoryStream())
            {
                file.CopyTo(ms);

                var result = new AssemblyManager(Database).UploadAssembly(ms.ToArray(), file.FileName);

                return RedirectToAction("Index", !result ? new { actionMessage = $"{_localizer["InvalidAssembly"]} ({file.FileName})" } : new {actionMessage = $"{_localizer["SuccessfullyUpload"]} {file.FileName}"});
            }
        }

        [HttpGet]
        [Access(AccessSections.ASSEMBLIES, AccessLevels.FULL)]
        public IActionResult DeleteAssembly(Guid id) =>
            RedirectToAction("Index",
                new AssemblyManager(Database).DeleteAssembly(id)
                    ? new {actionMessage = _localizer["SuccessfullyDeletedAssembly"] }
                    : new {actionMessage = _localizer["FailedToDeleteAssembly"] });

        [Access(AccessSections.ASSEMBLIES, AccessLevels.VIEW_ONLY)]
        public IActionResult Index(string actionMessage = null)
        {
            var model = new AssemblyDashboardModel()
            {
                AssembliesList = new AssemblyManager(Database).GetUploadedAssembliesList(),
                ActionMessage = actionMessage
            };

            return View(model);
        }
    }
}

src/DMTP.REST/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;

using DMTP.lib.Common;
using DMTP.lib.dal.Databases.Tables;
using DMTP.lib.dal.Manager;
using DMTP.lib.Managers;

using DMTP.REST.Models;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DMTP.REST.Controllers
{
    [Authorize]
    public class HomeController : BaseController
    {
        public HomeController(DatabaseManager database, Settings settings) : base(database, settings) { }

        public IActionResult Index()
        {
            var model = new HomeDashboardModel
            {
                Jobs = new JobManager(Database).GetJobs().Where(a => !a.Completed).OrderByDescending(a => a.SubmissionTime).ToList()
            };

            var assemblies = new AssemblyManager(Database).GetUploadedAssembliesList();

            model.ModelTypes = new List<SelectListItem>();

            foreach (var assembly in assemblies)
            {
                foreach (var predictor in assembly.Predictors)
                {
                    model.ModelTypes.Add(new SelectListItem(predictor, assembly.ID.ToString()));
                }
            }

            model.Workers = new WorkerManager(Database).GetWorkers().OrderBy(a => a.Name).ToList();

            model.AssignWorkers = new List<SelectListItem>
            {
                new SelectListItem(Constants.WORKER_AUTO_ASSIGN, Constants.WORKER_AUTO_ASSIGN)
            };

            model.AssignWorkers.AddRange(model.Workers.Select(a => new SelectListItem(a.Name, a.Name)));

            return View(model);
        }

        [HttpGet]
        public IActionResult AddJob([FromQuery]string name, [FromQuery]string trainingDataPath, [FromQuery]string modelType, [FromQuery]string selectedWorker)
        {
            var job = new Jobs
            {
                Name = name,
                TrainingDataPath = trainingDataPath,
                ModelType = modelType
            };

            if (selectedWorker != Constants.WORKER_AUTO_ASSIGN)
            {
                job.AssignedHost = selectedWorker;
            }

            SaveJob(job);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("/Download")]
        public FileResult Download([FromQuery]Guid id)
        {
            var job = new JobManager(Database).GetJob(id);

            return job == null ? 
                File(new byte[0], System.Net.Mime.MediaTypeNames.Text.Plain, "Model not found") : 
                File(job.Model, System.Net.Mime.MediaTypeNames.Application.Octet, $"{job.Name}.{Constants.MODEL_EXTENSION}");
        }
    }
}

src/DMTP.REST/Controllers/WorkersController.cs
using DMTP.lib.dal.Databases.Tables;
using DMTP.lib.dal.Manager;
using DMTP.lib.Managers;

using DMTP.REST.Models.Workers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DMTP.REST.Controllers
{
    [Authorize]
    public class WorkersController : BaseController
    {
        private string ComputeRegistrationKey() => CurrentSettings.DeviceKeyPassword;

        public WorkersController(DatabaseManager database, Settings settings) : base(database, settings)
        {
        }

        public IActionResult Index() => View(new WorkerListingModel
        {
            WorkersListing = new WorkerManager(Database).GetWorkers(),
            RegistrationKey = ComputeRegistrationKey(),
            WebServiceURL = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}/api/"
        });
    }
}

src/DMTP.REST/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

@model DMTP.REST.Models.HomeDashboardModel

@{
    ViewData["Title"] = Localizer["PageTitle"];
}

<h3>@Localizer["Header"]</h3>

@if (Model.ModelTypes.Any() && Model.Workers.Any())
{
    <form asp-action="AddJob" asp-controller="Home" method="get" class="form-inline">
        <div class="form-group" style="margin-right: 10px">
            <input type="text" placeholder="name" name="name" id="name" required class="form-control" style="max-width: 200px" />
        </div>

        <div class="form-group" style="margin-right: 10px">
            @Html.DropDownList("modelType", Model.ModelTypes, htmlAttributes: new { @class = "form-control" })
        </div>

        <div class="form-group" style="margin-right: 10px">
            @Html.DropDownList("SelectedWorker", Model.AssignWorkers, htmlAttributes: new { @class = "form-control" })
        </div>

        <div class="form-group" style="margin-right: 10px">
            <input type="text" placeholder="training data path" required name="trainingDataPath" id="trainingDataPath" class="form-control" style="max-width: 200px" />
        </div>

        <button type="submit" class="btn btn-secondary">@Localizer["AddJobButtonLabel"]</button>
    </form>
}
else
{
    <div class="text-white">
        @if (!Model.Workers.Any())
        {
            <p>No workers found, please proceed to <a asp-action="Index" asp-controller="Workers">Workers</a> to add Workers to your cluster</p>
        }

        @if (!Model.ModelTypes.Any())
        {
            <p>No Predictors found, please proceed to <a asp-action="Index" asp-controller="Assemblies">Assemblies</a> to add Predictors to your cluster</p>
        }
    </div>
}

<hr />

<h3>@Localizer["PendingJobsHeader"]</h3>
@if (Model.Jobs.Any())
{
    <partial name="_JobsListing" model="Model.Jobs" />
}
else
{
<p class="text-white">@Localizer["NoPendingJobs"]</p>
}

<h3>@Localizer["BusyWorkersHeader"]</h3>
@if (Model.Workers.Any(a => Model.Jobs.Any(b => b.AssignedHost == a.Name)))
{
    <partial name="_WorkersListing" model="Model.Workers" />
}
else
{
<p class="text-white">@Localizer["NoBusyWorkers"]</p>
}